import type { Metadata } from "next";
import clsx from "clsx";
import "./globals.css";

import { Inter, Playfair_Display } from "next/font/google";

import ThemeToggle from "@/components/ThemeToggle";
import ProfileDropdown from "@/components/DropdownMenu";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body
        className={clsx(
          "bg-light-background dark:bg-dark-background text-light-text dark:text-dark-text h-full",
          inter.className
        )}
      >
        <div className='flex h-screen'>
          {/* Left Aside */}
          <aside className='w-64 bg-light-aside border-r border-gray-200 dark:bg-dark-aside dark:border-gray-800 flex flex-col justify-between'>
            {/* Logo and Title */}
            <div className='p-4'>
              <h1 className='text-xl font-bold'>Project-404</h1>
            </div>
            {/* Conversations List */}
            <nav className='flex-1 overflow-y-auto p-4'>
              <ul className='space-y-2'>
                <li className='hover:bg-gray-300 dark:hover:bg-gray-700 p-2 rounded'>Conversation 1</li>
                <li className='hover:bg-gray-300 dark:hover:bg-gray-700 p-2 rounded'>Conversation 2</li>
              </ul>
            </nav>
          </aside>

          {/* Main Content */}
          <main className='flex-1 flex flex-col'>
            {/* Header Area */}
            <header className='flex items-center justify-end gap-4 p-4 border-b bg-light-background border-gray-200 dark:bg-dark-background dark:border-gray-800'>
              {/* Theme Switcher */}
              <ThemeToggle />
              {/* Profile Dropdown */}
              <ProfileDropdown />
              {/* Login/Logout/Link */}
              <button className='p-2 rounded-full bg-gray-300 dark:bg-gray-700'>Login</button>
            </header>

            {/* Main Content Area */}
            <section className='flex-1 p-6 overflow-auto'>{children}</section>
          </main>
        </div>
      </body>
    </html>
  );
}
